### ISSUE TITLE
DbUnitDataSet's "inherit" property does not work as expected

### ISSUE THREAD

**Issue by eeedean** [mjeanroy/dbunit-plus#216]
Hello everyone,

When using `@DbUnitDataSet` with `inherit=true`, one might expect, that the dataset of the class is being executed first and the dataset specified at the method second. Unfortunately the dataset specified at the method is being executed first, which might result in foreign key violations. 

```java
@DbUnitDataSet(value="/dbunit/bankaccounts.xml")
public class VeryImportantTests {
    @Test
    @DbUnitDataSet(value="/dbunit/transactions.xml", inherit = true)
    public void test() {
         System.out.println("this test is damn important, mate");
    }
}
```

in this case, I figured out, that in `DbUnitRunner.java` at line 181 the `IDataSet` is being loaded. And the debugger told me, that - in fact - all datasets are loaded, so it tries to populate `bankaccount` table as well as `transactions`. But unfortunately, at position 0 in the `_tables`-Array of the `AbstractDataSet` (value of `IDataSet` variable `dataSet`) the transactions are being held and at position 1 are the bankaccounts. That results - of course - in a foreign key violation, because you can't create transactions, if there are no bankaccounts, yet. Fortunately, one can work around bei specifying both datasets at the method level instead of using the `inherit` feature like so:

```java
@DbUnitDataSet(value="/dbunit/bankaccounts.xml")
public class VeryImportantTests {
    @Test
    @DbUnitDataSet(value={"/dbunit/bankaccounts.xml", "/dbunit/transactions.xml"})
    public void test() {
         System.out.println("this test is damn important, mate");
    }

    @Test
    public void alsoImportantButBaseDataIsSufficient() {
        System.out.println("I'm happily using the bankaccounts only!");
    }
}
```

Nevertheless, I would expect the `inherit` feature to be first running the dataset of the class level annotation and run the method level annotation afterwards. 

Thanks and best regards
Dean

**Comment by mjeanroy** [comment]
Hi @eeedean,
Your test case totally make sense, I'm going to fix it.
Just to be sure, what versions are you using?

**Comment by eeedean** [comment]
Hi @mjeanroy,
I‘m glad, I managed to describe the behaviour well 😀. I‘ve been using Version 2.0.1 while observing the behaviour. 

Best regards!
Dean

**Comment by mjeanroy** [comment]
@eeedean I just pushed a fix, if that is possible for you, would you mind to checkout the master branch and check that everything works for you with the current `master`? If your issue is fixed, I'll publish the fix on maven central.

**Comment by mjeanroy** [comment]
@eeedean Version 2.0.2 has just been published with the fix, feel free to test it and let me know if everything is ok on your side!

**Comment by eeedean** [comment]
Works perfectly. Thanks a lot! I highly appreciate your work. 😊
